services:
  rated_api:
    restart: unless-stopped
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/src/app
    environment:
      - ENV=development
    develop:
      watch:
        - action: sync
          path: /src
          target: /src
    depends_on:
      - rated_influxdb2

  rated_influxdb2:
    image: influxdb:2
    ports:
      - 8086:8086
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=${DOCKER_INFLUXDB_INIT_MODE}
      - DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET}
      - DOCKER_INFLUXDB_INIT_RETENTION=${DOCKER_INFLUXDB_INIT_RETENTION}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
      - DOCKER_INFLUXDB_INIT_ADMIN_USER=${DOCKER_INFLUXDB_INIT_ADMIN_USER}
      - DOCKER_INFLUXDB_INIT_ADMIN_PASSWORD=${DOCKER_INFLUXDB_INIT_ADMIN_PASSWORD}
      - INFLUXDB_HTTP_AUTH_ENABLED=${INFLUXDB_HTTP_AUTH_ENABLED}
    volumes:
      - type: volume
        source: influxdb2-data
        target: /var/lib/influxdb2
      - type: volume
        source: influxdb2-config
        target: /etc/influxdb2
    restart: unless-stopped

volumes:
  influxdb2-data:
  influxdb2-config: