networks:
  rated_network:
    driver: bridge

services:
#  rated_api:
#    restart: unless-stopped
#    build:
#      context: ./
#      dockerfile: src/app/Dockerfile
#    ports:
#      - "8000:80"
#    volumes:
#      - .:/src/app
#    networks:
#      - rated_network
#    develop:
#      watch:
#        - action: sync
#          path: /src
#          target: /src
#    depends_on:
#      - rated_influxdb2
  log_processor:
    build:
      context: ./
      dockerfile: src/log_processor/Dockerfile
    environment:
      - INFLUXDB_URL=${INFLUXDB_URL}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
      - DOCKER_INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET}
      - LOG_BATCH_SIZE=${LOG_BATCH_SIZE}
      - LOG_INTERVAL_SECONDS=${LOG_INTERVAL_SECONDS}
      - LOG_FILE_PATH=${LOG_FILE_PATH}
    depends_on:
      - rated_influxdb2
    volumes:
      - ./src/log_processor/:/log_processor/
      - ./src/log_generator/${LOG_FILE_PATH}:/log_generator/${LOG_FILE_PATH}
    networks:
      - rated_network
    restart: unless-stopped

  log_generator:
    build:
      context: ./
      dockerfile: src/log_generator/Dockerfile
    environment:
      LOG_BATCH_SIZE: ${LOG_BATCH_SIZE}
      LOG_INTERVAL_SECONDS: ${LOG_INTERVAL_SECONDS}
      LOG_FILE_PATH: ${LOG_FILE_PATH}
    volumes:
       - ./src/log_generator/:/log_generator/
    networks:
      - rated_network
    restart: unless-stopped

  rated_influxdb2:
    image: influxdb:2
    ports:
      - 8086:8086
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=${DOCKER_INFLUXDB_INIT_MODE}
      - DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET}
      - DOCKER_INFLUXDB_INIT_RETENTION=${DOCKER_INFLUXDB_INIT_RETENTION}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
      - DOCKER_INFLUXDB_INIT_ADMIN_USER=${DOCKER_INFLUXDB_INIT_ADMIN_USER}
      - DOCKER_INFLUXDB_INIT_ADMIN_PASSWORD=${DOCKER_INFLUXDB_INIT_ADMIN_PASSWORD}
      - INFLUXDB_HTTP_AUTH_ENABLED=${INFLUXDB_HTTP_AUTH_ENABLED}
    volumes:
      - ./influx-volume/data:/var/lib/influxdb2
      - ./influx-volume/config:/etc/influxdb2
    networks:
      - rated_network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8086/health" ]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  influxdb2-data:
  influxdb2-config: