networks:
  rated_network:
    driver: bridge

services:
  rated_api:
      container_name: rated_api
      build:
        context: ./
        dockerfile: ./src/api/Dockerfile
      ports:
        - "8000:8000"
      depends_on:
        - rated_db
      environment:
        - INFLUXDB_URL=${INFLUXDB_URL}
        - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
        - DOCKER_INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET}
        - DOCKER_INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG}
      networks:
        - rated_network
      restart: unless-stopped

  log_processor:
    container_name: log_processor
    build:
      context: ./
      dockerfile: ./src/log_processor/Dockerfile
    environment:
      - INFLUXDB_URL=${INFLUXDB_URL}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
      - DOCKER_INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET}
      - LOG_BATCH_SIZE=${LOG_BATCH_SIZE}
      - LOG_INTERVAL_SECONDS=${LOG_INTERVAL_SECONDS}
      - LOG_FILE_PATH=${LOG_FILE_PATH}
      - STREAM_MAX_SIZE=${STREAM_MAX_SIZE}
      - STREAM_MAX_WAIT_TIME_IN_SECONDS=${STREAM_MAX_WAIT_TIME_IN_SECONDS}
      - LOGGING_LEVEL=${LOGGING_LEVEL}
    depends_on:
      - rated_db
    networks:
      - rated_network
    restart: unless-stopped

  log_generator:
    container_name: log_generator
    build:
      context: ./
      dockerfile: ./src/log_generator/Dockerfile
    environment:
      LOG_BATCH_SIZE: ${LOG_BATCH_SIZE}
      LOG_INTERVAL_SECONDS: ${LOG_INTERVAL_SECONDS}
      LOG_FILE_PATH: ${LOG_FILE_PATH}
      MAX_LOGS_TO_GENERATE: ${MAX_LOGS_TO_GENERATE}
    networks:
      - rated_network
    depends_on:
      - log_processor
    restart: unless-stopped

  rated_db:
    container_name: rated_db
    image: influxdb:2
    ports:
      - 8086:8086
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=${DOCKER_INFLUXDB_INIT_MODE}
      - DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET}
      - DOCKER_INFLUXDB_INIT_RETENTION=${DOCKER_INFLUXDB_INIT_RETENTION}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
      - DOCKER_INFLUXDB_INIT_ADMIN_USER=${DOCKER_INFLUXDB_INIT_ADMIN_USER}
      - DOCKER_INFLUXDB_INIT_ADMIN_PASSWORD=${DOCKER_INFLUXDB_INIT_ADMIN_PASSWORD}
      - INFLUXDB_HTTP_AUTH_ENABLED=${INFLUXDB_HTTP_AUTH_ENABLED}
    networks:
      - rated_network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8086/health" ]
      interval: 10s
      timeout: 5s
      retries: 5