import os
from dotenv import load_dotenv

load_dotenv()

INFLUXDB_URL = os.getenv("INFLUXDB_URL")
INFLUXDB_TOKEN = os.getenv("DOCKER_INFLUXDB_INIT_ADMIN_TOKEN")
INFLUXDB_USERNAME = os.getenv("DOCKER_INFLUXDB_INIT_ADMIN_USER")
INFLUXDB_PASSWORD = os.getenv("DOCKER_INFLUXDB_INIT_ADMIN_PASSWORD")
INFLUXDB_ORG = os.getenv("DOCKER_INFLUXDB_INIT_ORG")
INFLUXDB_BUCKET = os.getenv("DOCKER_INFLUXDB_INIT_BUCKET")

LOG_BATCH_SIZE = int(os.getenv("LOG_BATCH_SIZE"))
LOG_INTERVAL_SECONDS = int(os.getenv("LOG_INTERVAL_SECONDS"))
LOG_FILE_PATH = os.getenv("LOG_FILE_PATH")