version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.12
    working_directory: ~/repo

jobs:
  test:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 27.2.0
      - run:
          name: Install Docker Compose
          command: |
            curl -L "https://github.com/docker/compose/releases/download/2.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - run:
          name: Make run_tests.sh Executable
          command: chmod +x ./run_tests.sh

      - run:
          name: Run Tests using run_tests.sh
          command: ./run_tests.sh

workflows:
  version: 2
  test-workflow:
    jobs:
      - run_tests